### PR TITLE
passing image factory

### LINKED ISSUE #32: Can not pass image_factory to qrcode.QRCode
It would be great to pass `image_factory` parameter, so it could be more integrated to e.g. https://github.com/ViktorStiskala/python-qrplatba

### LINKED ISSUE #34: No support for SVG qr codes
The rendering is hardcoded to use the https://github.com/lincolnloop/python-qrcode/blob/v7.3.1/qrcode/image/pil.py#L13, but it would be great, if it would deal with SVG in case the #32 would get resolved.

### PR DESCRIPTION
**Pull request by racinmat**
Fixes #32 
Fixes #34 
The tests which were already there did not work for me, so I just focused on adding new tests and making sure they work. This should not introduce any breaking changes.

### CODE REVIEW

**Comment by racinmat** [comment]
@marcoagner bump, what do you think, can this get merged?

**Comment by marcoagner** [comment]
Hey, @racinmat. I'll have a look at it later today. Thank you!

**Comment by racinmat** [comment]
@marcoagner is it looking good?

**Comment by marcoagner** [comment]
Thank you for your collaboration and sorry for unwittingly making you wait. But I've realized that I no longer have the interest or time to maintain this project.

**Pull request closed without merging**
